### ISSUE TITLE
Contact information for project owners?

### ISSUE THREAD

**Issue by CourtHive** [SlavLazurenko/TMS#38]
Hi... I'd like to learn more about this project.  I'm developing https://courthive.github.io/tods-competition-factory/  and https://courthive.github.io/tods-score-grid/?path=/story/score-grid-draw--multi-structure which seems like they could be very complimentary.

**Comment by SlavLazurenko** [comment]
Hello, @CourtHive nice to see you here! We can communicate through email. My name is Slav and my email is vlazurenko22@gmail.com

Please, CC my team members, so they can follow the conversation:
Sage Anthonypages009@gmail.com
Carlos carli96fiallo@yahoo.com
Bryant brymatt.rone@gmail.com
Jorge jorgelburgos12@gmail.com

Hope to hear from you soon.
